### ISSUE TITLE
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports'

### ISSUE THREAD

**Issue by ThatOneNerd0329** [slooi/NovelAI-Setup-Guide#12]
Traceback (most recent call last):
  File "/content/naifu/hydra_node/config.py", line 162, in init_config_model
    model = no_init(lambda: model_map[config.model_name](config))
  File "/content/naifu/hydra_node/config.py", line 34, in no_init
    result = loading_code()
  File "/content/naifu/hydra_node/config.py", line 162, in <lambda>
    model = no_init(lambda: model_map[config.model_name](config))
  File "/content/naifu/hydra_node/models.py", line 200, in __init__
    model, model_config = self.from_folder(config.model_path)
  File "/content/naifu/hydra_node/models.py", line 296, in from_folder
    model = self.load_model_from_config(model_config, model_path)
  File "/content/naifu/hydra_node/models.py", line 315, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/content/naifu/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/naifu/ldm/util.py", line 87, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/naifu/ldm/models/diffusion/ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/content/naifu/venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/content/naifu/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
  File "/content/naifu/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
  File "/content/naifu/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/progress/rich_progress.py", line 20, in <module>
    from torchmetrics.utilities.imports import _compare_version
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/content/naifu/venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py)
2023-07-09 05:12:27,004 ERROR config.py(3007) - Failed to load model: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/content/naifu/venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py)

**Comment by brskdrvgon** [comment]
same here

**Comment by EngsShi** [comment]
https://github.com/deforum-art/deforum-stable-diffusion/issues/285

this might solve your problem

**Comment by ThatOneNerd0329** [comment]
> [deforum-art/deforum-stable-diffusion#285](https://github.com/deforum-art/deforum-stable-diffusion/issues/285)
> 
> this might solve your problem

I see that the issue is that torchmetrics was updated recently causing the code to break but inserting torchmetrics==0.11.4 doesn't seem to work. Not sure if I'm doing something wrong or if the solution just doesn't work.

**Comment by brskdrvgon** [comment]
> > [deforum-art/deforum-stable-diffusion#285](https://github.com/deforum-art/deforum-stable-diffusion/issues/285)
> > this might solve your problem
> 
> I see that the issue is that torchmetrics was updated recently causing the code to break but inserting torchmetrics==0.11.4 doesn't seem to work. Not sure if I'm doing something wrong or if the solution just doesn't work.

https://colab.research.google.com/drive/15_sd1tymWK-HPK88iWb12AP8j0U8hZXG

Before run something...
Step 2. Paste it instead last line:
!/content/naifu/venv/bin/python -m pip install -qq pytorch_lightning==1.7.7 torchmetrics==0.11.4

**Comment by ThatOneNerd0329** [comment]
> > > [deforum-art/deforum-stable-diffusion#285](https://github.com/deforum-art/deforum-stable-diffusion/issues/285)
> > > this might solve your problem
> > 
> > 
> > I see that the issue is that torchmetrics was updated recently causing the code to break but inserting torchmetrics==0.11.4 doesn't seem to work. Not sure if I'm doing something wrong or if the solution just doesn't work.
> 
> https://colab.research.google.com/drive/15_sd1tymWK-HPK88iWb12AP8j0U8hZXG
> 
> Before run something... Step 2. Paste it instead last line: !/content/naifu/venv/bin/python -m pip install -qq pytorch_lightning==1.7.7 torchmetrics==0.11.4

It works thanks!
